# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 2


Vagrant.configure("2") do |config|


  config.vm.define "k8s-master" do |cfg|

    cfg.vm.box = "generic/ubuntu2004"
    cfg.vm.hostname = "master"
    cfg.vm.network "public_network", ip: "211.183.3.200", bridge: "br0", dev:"br0"

    cfg.vm.provider "libvirt" do |vb|
      vb.cpus = "2"
      vb.memory = "2048"
    end

    cfg.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
    SHELL

  end


  (1..N).each do |i|
    config.vm.define "k8s-worker#{i}" do |cfg|

      cfg.vm.box = "generic/ubuntu2004"

      cfg.vm.hostname = "worker#{i}"
      cfg.vm.network "public_network", ip: "211.183.3.20#{i}", bridge: "br0", dev:"br0"

      cfg.vm.provider "libvirt" do |vb|
        vb.cpus = "2"
        vb.memory = "2048"
      end

      cfg.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
      SHELL

    end
  end

end