# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 3

Vagrant.configure("2") do |config|
    config.vm.define "centos-m" do |cfg|
      cfg.vm.box = "generic/centos7"
      cfg.vm.host_name = "centos-m"
      cfg.vm.network :public_network, :bridge => "br0", :dev => "br0", ip:"211.183.3.201"
      cfg.vm.network "private_network", ip: "5.5.5.10"
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, id: "ssh"
      cfg.vm.provision "file", source: "bootstrap.sh", destination: "bootstrap.sh"
      cfg.vm.provision "shell", inline: "/bin/bash bootstrap.sh", privileged: true
      cfg.vm.provider :libvirt do |rsc|
        rsc.memory = 2048
        rsc.cpus = 2
      end
    end
    (1..N).each do |i|
    config.vm.define "centos-n#{i}" do |cfg|
      cfg.vm.box = "generic/centos7"
      cfg.vm.host_name = "centos-n#{i}"
      cfg.vm.network :public_network, :bridge => "br0", :dev => "br0", ip:"211.183.3.20#{i+1}"
      cfg.vm.network "private_network", ip: "5.5.5.1#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6001#{i}", id: "ssh"
      cfg.vm.provision "file", source: "bootstrap.sh", destination: "bootstrap.sh"
      cfg.vm.provision "shell", inline: "/bin/bash bootstrap.sh", privileged: true
      cfg.vm.provider :libvirt do |rsc|
        rsc.memory = 2048
        rsc.cpus = 2
      end
    end
  end
end
